### ISSUE TITLE
Import error when button Fig5BCD is pressed

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-gui#8]
Here is trace-back

~~~~
Traceback (most recent call last):
  File "mgui.py", line 271, in <lambda>
    button.clicked.connect(lambda x, script = k[1]: self.run_python_script(script))
  File "mgui.py", line 308, in run_python_script
    p = subprocess.Popen(["python", filename], cwd=directory)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/usr/lib/moose/moose-examples/paper-2015/Fig6_CellMultiscale'
~~~~~

Tested on MacOSX/OpenSUSE. The directory structure in package is following:

~~~~
gui/mgui.py 
moose-examples/*
~~~~~

**Comment by hrani** [comment]
Nothing to do with mac/OpenSUSE,  it was pass issue, corrected and added git 9df25bc72055ca4983e9397df7546c844b4a139c
